"""Agregar usuarios

Revision ID: 837eee030cd3
Revises: 7a43da8f6b10
Create Date: 2024-08-26 20:57:22.491884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837eee030cd3'
down_revision = '7a43da8f6b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=300), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
